apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-bio-react
  namespace: echo-bio
spec:
  selector:
    matchLabels:
      app: echo-bio-react
  template:
    metadata:
      labels:
        app: echo-bio-react
    spec:
      containers:
      - name: echo-bio-react
        image: airren/echo-bio-react:v0.0.26
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
