apiVersion: v1
kind: Service
metadata:
  name: echo-bio-react
  namespace: echo-bio
spec:
  selector:
    app: echo-bio-react
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088
  type: NodePort
